### PR TITLE
fix: refactore product card

### PR DESCRIPTION
**Pull request by DeidamiaFuentes**

### CODE REVIEW

**Review by Miguelito2774 — APPROVED** [review]
GG!

**Comment by Ronaldo-Miguel-Angel-Mendoza-Mallcu** [comment]
good job

**Review by Ronaldo-Miguel-Angel-Mendoza-Mallcu — APPROVED** [review]
Good job

**Comment by rencinasf** [comment]
@DeidamiaFuentes Are these the changes that were overwritten in the last sprint?

**Pull request merged**
